/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RecurringDetail'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RecurringDetail'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenApiJs) {
      root.AdyenApiJs = {};
    }
    root.AdyenApiJs.RecurringDetailContainer = factory(root.AdyenApiJs.ApiClient, root.AdyenApiJs.RecurringDetail);
  }
}(this, function(ApiClient, RecurringDetail) {
  'use strict';




  /**
   * The RecurringDetailContainer model module.
   * @module model/RecurringDetailContainer
   * @version 1.30.5
   */

  /**
   * Constructs a new <code>RecurringDetailContainer</code>.
   * @alias module:model/RecurringDetailContainer
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>RecurringDetailContainer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecurringDetailContainer} obj Optional instance to populate.
   * @return {module:model/RecurringDetailContainer} The populated <code>RecurringDetailContainer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('RecurringDetail')) {
        obj['RecurringDetail'] = RecurringDetail.constructFromObject(data['RecurringDetail']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/RecurringDetail} RecurringDetail
   */
  exports.prototype['RecurringDetail'] = undefined;


  /**
   * @return {module:model/RecurringDetail}
   */
  exports.prototype.getRecurringDetail = function() {
    return this['RecurringDetail'];
  }

  /**
   * @param {module:model/RecurringDetail} recurringDetail
   */
  exports.prototype.setRecurringDetail = function(recurringDetail) {
    this['RecurringDetail'] = recurringDetail;
  }



  return exports;
}));


